# Technical terminology glossary for Japanese-English translation
# Used by the intelligent translation system to preserve technical terms

terms:
  # Software development
  "API": "API"
  "REST API": "REST API"
  "GraphQL": "GraphQL"
  "SDK": "SDK"
  "フレームワーク": "Framework"
  "ライブラリ": "Library"
  "モジュール": "Module"
  "コンポーネント": "Component"
  "プラグイン": "Plugin"
  "ミドルウェア": "Middleware"
  
  # Database
  "データベース": "Database"
  "DB": "Database"
  "SQL": "SQL"
  "NoSQL": "NoSQL"
  "クエリ": "Query"
  "インデックス": "Index"
  "テーブル": "Table"
  "スキーマ": "Schema"
  "レコード": "Record"
  "フィールド": "Field"
  "主キー": "Primary Key"
  "外部キー": "Foreign Key"
  "正規化": "Normalization"
  "トランザクション": "Transaction"
  "バックアップ": "Backup"
  "リストア": "Restore"
  "レプリケーション": "Replication"
  "シャーディング": "Sharding"
  
  # Infrastructure
  "サーバー": "Server"
  "クライアント": "Client"
  "ネットワーク": "Network"
  "プロトコル": "Protocol"
  "HTTP": "HTTP"
  "HTTPS": "HTTPS"
  "TCP": "TCP"
  "UDP": "UDP"
  "IP": "IP"
  "DNS": "DNS"
  "CDN": "CDN"
  "ロードバランサー": "Load Balancer"
  "プロキシ": "Proxy"
  "ファイアウォール": "Firewall"
  "VPN": "VPN"
  
  # Cloud computing
  "クラウド": "Cloud"
  "AWS": "AWS"
  "Azure": "Azure"
  "GCP": "GCP"
  "IaaS": "IaaS"
  "PaaS": "PaaS"
  "SaaS": "SaaS"
  "コンテナ": "Container"
  "Docker": "Docker"
  "Kubernetes": "Kubernetes"
  "マイクロサービス": "Microservices"
  "サーバーレス": "Serverless"
  "Lambda": "Lambda"
  "EC2": "EC2"
  "S3": "S3"
  "RDS": "RDS"
  
  # Security
  "セキュリティ": "Security"
  "認証": "Authentication"
  "認可": "Authorization"
  "暗号化": "Encryption"
  "復号化": "Decryption"
  "ハッシュ": "Hash"
  "JWT": "JWT"
  "OAuth": "OAuth"
  "SSL": "SSL"
  "TLS": "TLS"
  "証明書": "Certificate"
  "秘密鍵": "Private Key"
  "公開鍵": "Public Key"
  "脆弱性": "Vulnerability"
  "攻撃": "Attack"
  "侵入": "Intrusion"
  "マルウェア": "Malware"
  "ウイルス": "Virus"
  
  # Programming
  "プログラム": "Program"
  "プログラミング": "Programming"
  "コード": "Code"
  "ソースコード": "Source Code"
  "アルゴリズム": "Algorithm"
  "データ構造": "Data Structure"
  "変数": "Variable"
  "関数": "Function"
  "メソッド": "Method"
  "クラス": "Class"
  "オブジェクト": "Object"
  "インスタンス": "Instance"
  "継承": "Inheritance"
  "ポリモーフィズム": "Polymorphism"
  "カプセル化": "Encapsulation"
  "抽象化": "Abstraction"
  "インターフェース": "Interface"
  "例外": "Exception"
  "エラー": "Error"
  "デバッグ": "Debug"
  "テスト": "Test"
  "単体テスト": "Unit Test"
  "統合テスト": "Integration Test"
  "リファクタリング": "Refactoring"
  
  # System operations
  "システム": "System"
  "OS": "Operating System"
  "Linux": "Linux"
  "Windows": "Windows"
  "macOS": "macOS"
  "プロセス": "Process"
  "スレッド": "Thread"
  "メモリ": "Memory"
  "CPU": "CPU"
  "GPU": "GPU"
  "ストレージ": "Storage"
  "ディスク": "Disk"
  "SSD": "SSD"
  "HDD": "HDD"
  "キャッシュ": "Cache"
  "バッファ": "Buffer"
  "ログ": "Log"
  "監視": "Monitoring"
  "アラート": "Alert"
  "メトリクス": "Metrics"
  "パフォーマンス": "Performance"
  "最適化": "Optimization"
  "スケーリング": "Scaling"
  "可用性": "Availability"
  "冗長性": "Redundancy"
  
  # Development tools
  "IDE": "IDE"
  "エディタ": "Editor"
  "コンパイラ": "Compiler"
  "インタープリター": "Interpreter"
  "デバッガー": "Debugger"
  "プロファイラー": "Profiler"
  "Git": "Git"
  "GitHub": "GitHub"
  "GitLab": "GitLab"
  "バージョン管理": "Version Control"
  "ブランチ": "Branch"
  "マージ": "Merge"
  "コミット": "Commit"
  "プルリクエスト": "Pull Request"
  "CI/CD": "CI/CD"
  "ビルド": "Build"
  "デプロイ": "Deploy"
  "リリース": "Release"
  
  # Data and AI
  "データ": "Data"
  "ビッグデータ": "Big Data"
  "データサイエンス": "Data Science"
  "機械学習": "Machine Learning"
  "AI": "AI"
  "人工知能": "Artificial Intelligence"
  "ディープラーニング": "Deep Learning"
  "ニューラルネットワーク": "Neural Network"
  "アルゴリズム": "Algorithm"
  "モデル": "Model"
  "トレーニング": "Training"
  "推論": "Inference"
  "予測": "Prediction"
  "分類": "Classification"
  "回帰": "Regression"
  "クラスタリング": "Clustering"
  "特徴量": "Feature"
  "データセット": "Dataset"
  "ラベル": "Label"
  "教師あり学習": "Supervised Learning"
  "教師なし学習": "Unsupervised Learning"
  "強化学習": "Reinforcement Learning"