# Intelligent Translation Configuration for Kurachi AI
# Production-ready settings for Japanese-English business translation

# Quality thresholds and gates
quality:
  thresholds:
    high: 0.85      # Accept immediately
    medium: 0.70    # Back-translation spot-check
    low: 0.50       # Fallback + recheck
  
  # Language pair specific length ratios
  length_ratios:
    ja_to_en:
      min: 1.0      # Japanese to English typically expands
      max: 1.8
      ideal: 1.3
    en_to_ja:
      min: 0.6      # English to Japanese typically contracts  
      max: 1.2
      ideal: 0.9
    default:
      min: 0.8
      max: 1.2
      ideal: 1.0

  # Back-translation settings
  back_translation:
    enabled: true
    trigger_threshold: 0.85   # Only BT if quality < 0.85
    chrf_threshold: 0.70      # Minimum chrF score to accept
    fallback_on_fail: true    # Use Helsinki if BT fails

# Cache configuration
cache:
  enabled: true
  ttl_days: 30              # Cache entries expire after 30 days
  max_entries: 10000        # Maximum cache entries
  cleanup_interval: 24      # Hours between cache cleanup
  
  # Cache key components
  key_components:
    - "normalized_text"
    - "source_language"
    - "target_language" 
    - "domain"
    - "glossary_version"
    - "style"

# LLM settings
llm:
  temperature: 0.0          # Deterministic translations
  timeout: 30               # Seconds
  max_tokens: 2048
  retry_attempts: 2
  
  # Prompt optimization
  prompts:
    use_json_glossary: true
    enforce_glossary: true
    preserve_formatting: true
    business_context: true

# Domain classification
domain_detection:
  enabled: true
  keywords:
    business:
      - "quarterly"
      - "revenue" 
      - "profit"
      - "stakeholder"
      - "ROI"
      - "KPI"
      - "四半期"
      - "売上"
      - "利益"
      - "御社"
      - "弊社"
    technical:
      - "API"
      - "database"
      - "algorithm"
      - "machine learning"
      - "artificial intelligence"
      - "データベース"
      - "アルゴリズム"
      - "機械学習"
      - "人工知能"
    legal:
      - "contract"
      - "agreement"
      - "liability"
      - "compliance"
      - "契約"
      - "合意"
      - "責任"
      - "コンプライアンス"

# Glossary enforcement
glossary:
  enforcement:
    enabled: true
    strict_mode: false      # If true, reject translations missing required terms
    retry_on_miss: true     # Re-prompt if glossary terms missing
    max_retries: 2
  
  # Glossary versioning
  versioning:
    enabled: true
    auto_invalidate: true   # Invalidate cache on glossary updates
    
  # Term priority
  priority_terms:
    high:
      - "御社"
      - "弊社" 
      - "quarterly results"
      - "ROI"
    medium:
      - "stakeholder"
      - "deliverable"
    low: []

# Special handling
special_handling:
  # Code blocks - never translate
  code_blocks:
    preserve: true
    patterns:
      - "```.*?```"
      - "`.*?`"
      - "SELECT.*?;"
      - "function.*?\\(.*?\\)"
  
  # Named entities - preserve
  named_entities:
    preserve: true
    types:
      - "PERSON"
      - "ORG" 
      - "PRODUCT"
      - "GPE"  # Geopolitical entities
  
  # Numbers and dates - preserve exactly
  preserve_exact:
    - "\\d{4}-\\d{2}-\\d{2}"    # ISO dates
    - "\\d+\\.\\d+%"            # Percentages
    - "\\$\\d+(?:,\\d{3})*"     # Currency
    - "\\d+(?:,\\d{3})*"        # Large numbers

# Fallback configuration  
fallback:
  enabled: true
  methods:
    - "helsinki_opus"         # Helsinki-NLP models
    - "basic_translation"     # Existing translation service
  
  # When to use fallback
  triggers:
    - "quality_too_low"       # Quality < low threshold
    - "llm_timeout"           # LLM call timeout
    - "glossary_enforcement_failed"  # Required terms missing
    - "back_translation_failed"     # BT score too low

# Logging and monitoring
logging:
  level: "INFO"
  log_translations: true
  log_quality_scores: true
  log_cache_hits: true
  log_fallbacks: true
  
  # Quality monitoring
  quality_alerts:
    enabled: true
    low_quality_threshold: 0.60   # Alert if avg quality drops below
    cache_miss_threshold: 0.30    # Alert if cache miss rate > 30%

# Performance optimization
performance:
  batch_processing:
    enabled: true
    max_batch_size: 10
    timeout_per_item: 15
  
  # Concurrent processing
  concurrency:
    max_workers: 3
    queue_size: 50
  
  # Memory management
  memory:
    max_cache_size_mb: 100
    cleanup_on_memory_pressure: true

# UI integration settings
ui:
  show_quality_scores: true
  show_glossary_hits: true
  show_original_text: true
  enable_manual_correction: true
  
  # Language preferences
  default_source: "auto"
  default_target: "en"
  supported_pairs:
    - ["ja", "en"]
    - ["en", "ja"]
    - ["zh-cn", "en"] 
    - ["ko", "en"]

# Development and testing
development:
  debug_mode: false
  save_prompts: false
  mock_llm: false
  test_glossary_coverage: true